import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/TopNav";
import Footer from "@/components/Footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"]
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export const viewport: Viewport = {
	themeColor: "#010101" // only hard-coded here because server-side
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={htmlContainerStyling}>
			<body className={bodyContainerStyling}>
				<TopNav />
				{children}
				<Footer />
			</body>
		</html>
	);
}

const htmlContainerStyling = `
	flex
	justify-center
`;

const bodyContainerStyling = `
	${geistSans.variable}
	${geistMono.variable}
	flex
	flex-col
	h-screen
	w-full
	items-center
	max-w-[2000px]
`;
